#配置数据库信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:/ip:3306/myblog?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=GMT%2b8&autoReconnect=true
    username: yourusername
    password: databasepassword
#url:访问地址，username :数据库用户名 password:数据库密码

#指定mybatisPlus扫描的xml文件
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

#指定端口
server:
  port: 8089

hikari:
  connection-timeout: 30000   # 数据库连接超时时间,默认30秒,即30000
  validation-timeout: 3000    # 指定验证连接有效性的超时时间(默认是5秒,最小不能小于250毫秒)
  idle-timeout: 60000         # 空闲连接超时时间,一个连接idle状态的最大时长（毫秒）,超时则被释放（retired）,默认是10分钟,只有空闲连接数大于最大连接数且空闲时间超过该值,才会被释放
  login-timeout: 5            # 指定连接数据库的超时时间,单位:秒
  max-lifetime: 29000         # 指定连接池中连接的最大生存时间,单位:毫秒.默认是1800000,即30分钟
  maximum-pool-size: 30       # 指定连接池最大的连接数,包括使用中的和空闲的连接,默认值10
  minimum-idle: 10            # 指定连接维护的最小空闲连接数,当使用HikariCP时指定
  read-only: false            # 当使用Hikari connection pool时,是否标记数据源只读